### ISSUE TITLE
Full discovery returns duplicate entries 

### ISSUE THREAD

**Issue by gortegaMS** [retaildevcrews/ServicePrincipal#489]
## Description

Investigate why full seed discovery returns duplicate entries for some Service Principals 

## Expected Behavior

GetDeltaGraphObjects method should not return duplicate items 

## Reproduce

1. Run Full discovery 
2.  Inspect servicePrincipalList before it gets returned
3. See attached screenshot 

## Additional Context

![image](https://user-images.githubusercontent.com/70150605/103309486-d2025b00-49da-11eb-8316-bbfd173a2413.png)

**Comment by jkeane** [comment]
This is expected behavior from the the delta query (https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/6037).  We need to change our logic to de-dupe entries.
